version: "2.2"
services:
  web: 
    image: php:7.2-apache  
    ports:
      - 8080:80
  db:
    image: mysql:latest
    volumes:
      - '~/mysql:/var/lib/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=ottria
