version: "2.2"
services:
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=ottria
  web: 
   #image: php:7.2-apache
    build: .
    ports:
      - 8080:80
      - 8043:443
    volumes:
      - ./php:/var/www/html